# R packages

_As part of assignment 8 from the [DSFB2 Workflows course](https://lesmaterialen.rstudio.hu.nl/workflows-reader/#course-introduction)._

----

For this assignment the previous assignments will be analysed to check for any repetitive code. This code will be turned into functions, combined into my first R package. 

## The Demo

The [Whole Game demo](https://r-pkgs.org/whole-game.html) made by Hadley Wickham was followed to start creating the R package. This demo was a complete guide through setting up the package, connecting it to Git and writing the first function. It went over useful packages like roxygen2 and testthat. A short summary of packages and functions was made based on what I learned in the demo for later use.

<details><summary><i>R package building cheatsheet</i></summary>
<b>Useful libraries:</b><br>
library(devtools)<br>
library(usethis)<br>
library(roxygen2)<br>
library(testthat)<br>

<b>How roxygen2 works:</b>
<ol><li>Put cursor in function</li>
<li>Code -> insert roxygen skeleton/li>>
<li>Fill in necessary details</li></ol>

<b>Important functions:</b><br>
create_package("~/path/to/package/packaganame")<br>
-- Creates package

use_git()<br>
-- Connects to git

use_r("filename")<br>
-- Opens/creates script in R/

load_all()<br>
-- Loads all functions without using globalenv

exists("function", where = globalenv(), inherits = FALSE)<br>
-- Checks if function exists in globalenv

check()<br>
-- Checks entire package for errors/warnings/notes

use_mit_license()<br>
-- Sets license to MIT

document()<br>
-- Creates/updates the manuals in man/ based on roxygen<br>
-- Updates the NAMESPACE file

install()<br>
-- Installs the package

use_testthat()<br>
-- Declares our intent to write tests<br>
-- Creates test directories

use_test("functionname")<br>
-- Opens/create a testfile

test()<br>
-- Performs all tests

use_package("packagename")<br>
-- Add a package to import in DESCRIPTION

rename_files("oldname", "newname")<br>
-- Rename files

use_readme_rmd()<br>
-- Writes README template<br>
-- Adds readme to the ignore file

build_readme()<br>
-- Updates the readme.md file based on the readme.rmd
</details>

## RMarkdown driven development

In the Workflows course the use of "Start with RMarkdown" was emphasized. This style of creating an R package does not start from zero like the demo suggested. It is based on a pre-written RMarkdown and the scripts that came with it. 

There are a lot of advantages to creating a complete all-in-one package when sharing a RMarkdown based analysis for others to reproduce. Usually, this sharing happens through an RMarkdown, some functions, the tidy version of the data, the steps used to get it tidy, the analysis itself and the used packages. These are multiple separate elements for someone to go over before they can reproduce the analysis. It can be made a lot more efficient by taking a few extra steps to create an R package from the RMarkdown. This way the elements are combined in one unit which is easily shared and can be used for multiple purposes and on different datasets.

## Package "portrobbo"

For this assignment we were asked to create a package which supports our portfolio. This will make the RMarkdowns more fluid and reduce duplicated code. It can also be used for later analysis.

### Picking a name

To find an available but still meaningful name I wanted to combine the word 'portfolio' with my partner's name. My partner happens to work on ships so the name portrobbo, combining the words 'portfolio', 'port' and his name, came to mind. After checking the availability I decided to use that as the name for my first R package. After setting up the project for the package and the [github repository](https://github.com/mirthhe/portrobbo) it was ready for it's first function. 

### The functions

After going over my written code, it was difficult to find duplications. For most assignments no code was written, except for assignment 1 and assignment 7. In the end, three functions have been made which shorten the code slightly and will be useful for future projects. For a longer explanation and manual, visit the package's [github repository](https://github.com/mirthhe/portrobbo).
<ul><li>save_csv_rds() -> saves a dataframe in .csv and .rds format</li>
<li>graph_cap() -> wraps a string at 80 characters so it fits well in the graphs format</li>
<li>graph_jitter -> shortens the positon_jitter function to only have one number as input</li></ul>
More functions will be added as the portfolio develops and expands.