# Groupproject

_As part of assignment 5 from the [DSFB2 Workflows course](https://lesmaterialen.rstudio.hu.nl/workflows-reader/#course-introduction)._

----

Alongside the subject of Workflows we will be working in groups of three students on a project. With this project we will learn about agile methods of collaboration, apply our data science skills, create a working product and present this product. In our case we are working on a project revolving around [ONTOX](https://ontox-project.eu/) with Marc Teunis as our cliënt. 

----

## Technology to reduce animaltesting

A goal I have within my career is reducing the need for animaltesting in biomedical research. Within the field of animaltesting there's a focus on replacement, reduction and refinement, as described by @simmondsBioethicsAnimalUse2018.

In the past replacement focussed on insentient material and animal species "lower" on the pylogenic scale. In recent years the use of computer software as a replacement is becoming more and more relevant [@grafstromReplacementAnimalExperiments2015]. Reduction focuses on properly designing the research so less animals are used and to prevent the need for more animals than initially expected. This becomes complicated when using less animals for the inital research may create the need for more animals in repetitive or supporting studies. In this case using software would not only reduce the amount of animals needed, it would also make reproduction a lot easier. The third R, refinement, is all about reducing the amount of discomfort the animals go through. This can include training the animals to get used to the treatment with positive reinforcement or the use of anesthesia [@simmondsBioethicsAnimalUse2018]. This takes more time and resources which can be prevented by using computer software instead.

One project with a focus on reducing the need for animals in human risk assessment of chemicals is the ONTOX project. 

----

## ONTOX

In their own words "The vision of the ONTOX consortium is to provide a functional and sustainable solution for advancing human risk assessment of chemicals without the use of animals in line with the principles of 21st century toxicity testing and next generation risk assessment" [@ONTOXProject]. One of the ways to achieve this is by collecting and combining existing data to be used in the risk assessment. Platforms like SysRev are able to extract useful data from articles. This data consists of metabolic pathways and interactions between compounds. To make the data useful for computerbased analysis it is formatted into what is called an SBtab file. This file, in turn, can be used to create visualisations of the metabolic pathways or it can be turned into other formats like SBML. Different apps (i.e. Phymdos) and functions have been created to execute these possibilities.

----

## SYSREV

Our current knowledge within the biomedical industry consists of big and complex datasets. Combining the datasets from multiple sources
can help with identifying clusters and correlation between datasets, as well as developing predictive models [@ristevskiBigDataAnalytics2018]. The amount of existing literature and data is hard to grasp. One way to make this easier is by using software platforms like SysRev. SysRev is a collaborative platform for the extraction of data from documents [@BuiltDataMiners]. It speeds up the extraction of useful data from documents by presenting it in a shorter format. This researcher will be able to go over more data in the same amount of time.

Existing data about risk assessment on humans may be more accurate than performing the same risk assessment on a new samplegroup of animals. As shown by @perelComparisonTreatmentEffects2007 the treatment effects in animal experiments can differ greatly from the ones in clinical trials. Simon Festing, executive director of RDS, once stated "Animals are better used for understanding disease mechanisms and potential new treatments, rather than predicting what will happen in humans," [@TroubleAnimalModels]. In order to predict risk in humans it is important to look at our specific biological systems instead of other organisms. Aside from performing clinical trials the existing data should be used more optimally.

----

## SBtab and Phymdos

One of the possible output formats used by SysRev is called SBtab. This format is a set of syntax rules, created to simplify data processing, and can be interconverted with the well known SBML format [@SBtabStandardisedData]. One app which can perform this conversion is [Phymdos](https://rstudio-connect.hu.nl/phymdos/). The app was created by D. Roodzant for University of Applied Sciences Utrecht. It can take SBtab files, SBML files or extract them directly from SysRev. It allows the user to create SBML style physiological maps in the desired format. This app demonstrates the range of possiblities with this type of data.

----

## The Goal

The current process of extracting and analyzing SBtab files is only applicable to single files. Looking ahead, ONTOX strives to improve human risk assessment by combining multiple sources for the same goal. In order to use this existing process for the bigger picture, it should be combining data instead of looking at one particular set. This is why Marc Teunis asked us to make an R package with the following functions:
<ol>
<li>Extract the SBtab data from SysRev for one or more articles.</li>
<li>Merge multiple SBtab files into one new file.</li>
<li>Create a graph, visualizing the data based on the merged SBtab file.</li>
<li>Convert the SBtab file to another format like SBML.</li>
</ol>
